from __future__ import annotations

from collections.abc import Iterator
from collections.abc import Mapping
from collections.abc import Sequence

class DataType: ...
class Scalar: ...
class Array: ...

class Field:
    name: str
    type: DataType
    nullable: bool

class Schema:
    def __iter__(self) -> Iterator[Field]: ...

class RecordBatch:
    def to_pylist(self) -> list[dict[str, object | None]]: ...

class GroupedTable:
    def aggregate(self, aggregations: Sequence[tuple[str, str]]) -> Table: ...

class Table:
    num_rows: int

    @classmethod
    def from_arrays(cls, arrays: Sequence[Array], schema: Schema) -> Table: ...
    def __getitem__(self, key: str) -> object: ...
    def filter(self, mask: object) -> Table: ...
    def group_by(self, keys: Sequence[str]) -> GroupedTable: ...
    def join(
        self,
        right_table: Table,
        keys: Sequence[str],
        join_type: str = ...,
    ) -> Table: ...
    def rename_columns(self, names: Sequence[str]) -> Table: ...
    def select(self, columns: Sequence[str]) -> Table: ...
    def sort_by(self, sorting: Sequence[tuple[str, str]]) -> Table: ...
    def to_batches(self, max_chunksize: int = ...) -> list[RecordBatch]: ...

def array(values: Sequence[object | None], type: DataType | None = ...) -> Array: ...
def binary(byte_width: int | None = ...) -> DataType: ...
def bool_() -> DataType: ...
def field(name: str, data_type: DataType, nullable: bool = ...) -> Field: ...
def int64() -> DataType: ...
def scalar(value: object | None, type: DataType | None = ...) -> Scalar: ...
def schema(fields: Sequence[Field]) -> Schema: ...
def string() -> DataType: ...
def table(data: Mapping[str, Array]) -> Table: ...
def timestamp(unit: str, tz: str | None = ...) -> DataType: ...
def uint64() -> DataType: ...
def uint8() -> DataType: ...
