from __future__ import annotations

def add(left: object, right: object) -> object: ...
def and_kleene(left: object, right: object) -> object: ...
def binary_length(value: object) -> object: ...
def cast(value: object, data_type: object) -> object: ...
def equal(left: object, right: object) -> object: ...
def fill_null(value: object, replacement: object) -> object: ...
def greater(left: object, right: object) -> object: ...
def invert(value: object) -> object: ...
def is_null(value: object) -> object: ...
def not_equal(left: object, right: object) -> object: ...
def or_kleene(left: object, right: object) -> object: ...
def subtract(left: object, right: object) -> object: ...
